import type { SubtitleCue, SubtitleStyle } from "@/lib/subtitles/types";
import type { TimelineDocument } from "@/lib/timeline/types";

export type EditorElementType =
  | "video"
  | "image"
  | "audio"
  | "text"
  | "shape"
  | "subtitle";

export type EditorElement = {
  id: string;
  type: EditorElementType;
  trackIndex: number;
  startMs: number;
  endMs: number;
  mediaAssetId?: string;
  audioAssetId?: string;
  mediaUrl?: string;
  mediaName?: string;
  localPath?: string | null;
  text?: string;
  shape?: "rectangle" | "circle" | "triangle" | "star";
  style?: Record<string, unknown>;
  position?: { x: number; y: number };
  size?: { width: number; height: number };
  opacity?: number;
  rotation?: number;
  fit?: "cover" | "contain" | "fill";
  locked?: boolean;
  visible?: boolean;
  waveformPeaks?: number[] | null;
  /** Per-cue subtitle when type is subtitle */
  cueId?: string;
  /** Text animation config */
  animation?: {
    entrance?: string;
    exit?: string;
    continuous?: string;
  };
  /** Metadata for auto-generated text overlays */
  textOverlayMeta?: {
    category?: string;
    isAutoGenerated?: boolean;
  };
  /** Source trim offset in ms (video/audio) */
  trimStartMs?: number;
  /** Per-clip audio mixer (video sound + audio clips). */
  muted?: boolean;
  volume?: number;
  playbackRate?: number;
};

export type EditorTrack = {
  id: string;
  type: "video" | "audio" | "text" | "subtitle" | "overlay";
  name: string;
  locked: boolean;
  visible: boolean;
};

export type EditorAspectRatio = {
  label: "9:16" | "16:9" | "1:1";
  width: number;
  height: number;
};

export type EditorExportJob = {
  id: string;
  status: string;
  renderProgress: number;
  downloadUrl: string | null;
  errorMessage: string | null;
};

export type EditorExportResolution = "1080x1920" | "1920x1080" | "1080x1080";
export type EditorExportFormat = "mp4" | "webm";

export type ProjectAssetsInput = {
  projectId: string;
  audio?: {
    id: string;
    r2Url: string;
    durationMs: number;
    waveformData?: unknown;
    localPath?: string | null;
    r2Key?: string;
  } | null;
};

export type LoadedProjectAssets = {
  media: Array<{
    id: string;
    type: string;
    originalName: string;
    r2Url: string;
    thumbnailUrl?: string | null;
    localPath?: string | null;
    r2Key?: string;
  }>;
  timeline: TimelineDocument | null;
  timelineId: string | null;
  subtitleCues: SubtitleCue[];
  subtitleStyle: SubtitleStyle;
  subtitlePresetName?: string;
  subtitleTrackId: string | null;
  elements: EditorElement[];
  durationMs: number;
  warnings: string[];
};
