import prisma from "@/lib/db/prisma";
import { cuesToEditorCaptions, parseCuesJson } from "@/lib/subtitles/cues";
import { resolveSubtitleStyle, TITLE_FACT_CATEGORY_LABELS, stripFactCategoryPrefix } from "@/lib/subtitles/presets";
import type { SubtitleStyle } from "@/lib/subtitles/types";

function titleTextFromValue(key: string, value: unknown): string[] {
  const label = TITLE_FACT_CATEGORY_LABELS[key] ?? key.replace(/([A-Z])/g, " $1").trim();
  if (value == null || value === "") return [];
  if (typeof value === "boolean") return value ? [label] : [];
  if (typeof value === "string" || typeof value === "number") {
    const s = String(value).trim();
    return s ? [stripFactCategoryPrefix(s)] : [];
  }
  if (!Array.isArray(value)) return [];

  return value.flatMap((item) => {
    if (item == null || item === "") return [];
    if (typeof item === "string" || typeof item === "number") {
      const s = String(item).trim();
      return s ? [stripFactCategoryPrefix(s)] : [];
    }
    if (typeof item === "object") {
      const values = Object.values(item as Record<string, unknown>)
        .filter((v) => v != null && v !== "")
        .join(" ");
      return values ? [stripFactCategoryPrefix(values)] : [];
    }
    return [];
  });
}

function buildTitleRowsFromFacts(facts: unknown, durationMs?: number): any[] {
  const existingRows = Array.isArray(facts)
    ? facts.filter((fact): fact is any => typeof fact?.text === "string")
    : [];
  
  const texts: any[] = existingRows.length > 0
    ? existingRows.map((fact) => ({
      id: typeof fact.id === "string" ? fact.id : undefined,
      text: fact.text,
      category: fact.category,
      startMs: typeof fact.startMs === "number" ? fact.startMs : undefined,
      endMs: typeof fact.endMs === "number" ? fact.endMs : undefined,
    }))
    : facts && typeof facts === "object"
      ? Object.entries(facts as Record<string, unknown>).flatMap(([key, value]) =>
        titleTextFromValue(key, value).map((text, index) => ({
          id: `${key}-${index}`,
          text,
          category: TITLE_FACT_CATEGORY_LABELS[key] ?? key,
        }))
      )
      : [];

  const visibleTexts = texts.filter((row) => row.text.trim()).slice(0, 8);
  const totalMs = Math.max(durationMs ?? 0, visibleTexts.length * 3000, 3000);
  const slotMs = Math.max(2500, Math.floor(totalMs / Math.max(visibleTexts.length, 1)));

  return visibleTexts.map((row, index) => {
    const startMs = row.startMs ?? index * slotMs;
    const endMs = row.endMs ?? Math.min(totalMs, startMs + slotMs);
    return {
      id: row.id ?? `title-${index}`,
      text: row.text.trim(),
      category: row.category,
      startMs,
      endMs: Math.max(startMs + 250, endMs),
    };
  });
}

export async function getEditorBootstrap(projectId: string, userId: string) {
  const project = await prisma.project.findFirst({
    where: { id: projectId, userId },
    include: {
      mediaAssets: {
        orderBy: { createdAt: "desc" },
      },
      audioAssets: {
        orderBy: { createdAt: "desc" },
        take: 1,
      },
      subtitleTracks: {
        orderBy: { createdAt: "desc" },
        take: 1,
      },
      timelines: {
        orderBy: [
          { version: "desc" },
          { createdAt: "desc" }
        ],
        take: 1,
      }
    }
  });

  if (!project) return null;

  const audio = project.audioAssets[0];
  const subtitles = project.subtitleTracks[0];

  let captions = undefined;
  if (subtitles?.cues) {
    captions = cuesToEditorCaptions(parseCuesJson(subtitles.cues));
  }

  const timeline = project.timelines[0];
  let titleCards: any[] = [];
  
  if (timeline?.clips && typeof timeline.clips === "object") {
    const clips = Object.values(timeline.clips) as any[];
    
    // 1. Try to find user custom titles (category === "title")
    let titleClips = clips.filter((c: any) => {
      if (c?.type !== "text" && c?.kind !== "text" && c?.kind !== "subtitle") return false;
      const meta = c?.properties?.textOverlayMeta;
      const isSubtitle = c?.trackId === "track-subtitle" || meta?.category === "subtitle";
      if (isSubtitle) return false;
      return meta?.category === "title";
    });
    
    // 2. If no custom titles, fallback to auto-generated fact/title clips
    if (titleClips.length === 0) {
      titleClips = clips.filter((c: any) => {
        if (c?.type !== "text" && c?.kind !== "text" && c?.kind !== "subtitle") return false;
        const meta = c?.properties?.textOverlayMeta;
        const isSubtitle = c?.trackId === "track-subtitle" || meta?.category === "subtitle";
        if (isSubtitle) return false;
        return meta?.isAutoGenerated === true || c?.trackId === "track-facts" || c?.trackId === "track-text";
      });
    }

    titleCards = titleClips.map((c: any) => {
      const metaStyle = c.properties?.textOverlayMeta?.titleStyle;
      const propStyle = c.properties?.style;
      const bgOpacity = propStyle?.backgroundColor?.match(/rgba?\([^,]+,[^,]+,[^,]+,\s*([\d.]+)\)/)
        ? Math.round(parseFloat(propStyle.backgroundColor.match(/rgba?\([^,]+,[^,]+,[^,]+,\s*([\d.]+)\)/)[1]) * 100)
        : 0;

      const titleStyle = metaStyle || (propStyle ? {
        fontFamily: propStyle.fontFamily,
        fontSize: propStyle.fontSize,
        fontWeight: propStyle.fontWeight,
        color: propStyle.color,
        backgroundOpacity: bgOpacity,
        fontStyle: propStyle.fontStyle,
        textDecoration: propStyle.textDecoration,
        letterSpacing: propStyle.letterSpacing,
        shadow: propStyle.shadow !== false,
      } : undefined);

      return {
        id: c.id,
        text: c.properties?.text || "",
        startMs: c.startTime || 0,
        endMs: c.endTime || 0,
        titleStyle,
      };
    });
  }

  // 3. Fallback to generating title cards from extractedFacts if timeline has no title clips
  if (titleCards.length === 0 && project.extractedFacts) {
    const fallbackRows = buildTitleRowsFromFacts(project.extractedFacts, audio?.durationMs);
    titleCards = fallbackRows.map((row) => ({
      id: row.id,
      text: row.text,
      startMs: row.startMs,
      endMs: row.endMs,
      titleStyle: undefined, // Will fallback to default preset in store
    }));
  }

  return {
    title: project.title,
    voiceUrl: audio?.r2Url,
    voiceDuration: audio ? audio.durationMs / 1000 : undefined,
    captions,
    titleCards,
    subtitleStyle: resolveSubtitleStyle(
      subtitles?.stylePreset ?? "instagram_reels",
      subtitles?.customStyle ? (subtitles.customStyle as SubtitleStyle) : null,
    ),
    projectMedia: project.mediaAssets.map((m) => ({
      mediaAssetId: m.id,
      name: m.originalName,
      kind: m.mimeType.startsWith("audio/") ? "audio" : m.mimeType.startsWith("video/") ? "video" : "image",
      src: m.r2Url,
      duration: Math.round((m.durationMs || 0) / 1000),
      size: m.fileSizeBytes ?? 0,
      thumb: m.thumbnailUrl ?? undefined,
    })),
  };
}
